name: Java CI with Maven

on:
  push:
    branches: [ "phu" ]
  pull_request:
    branches: [ "phu" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-binary
        path: target/*.jar